
# STACK AND QUEUES

# A stack is a data structure that can hold many elements. 
#   Last In First Out. think of a book on a table stacked

# Basic operations we can do on a stack are:

# Push:    Adds a new element on the stack.
# Pop:     Removes and returns top element from the stack.
# Peek:    Returns the top element on the stack.
# isEmpty: Checks if the stack is empty.
# Size:    Finds the number of elements in the stack.


#--------------------------------------------------------------------------------

# A queue is a data structure that can hold many elements. think of it as  a line LIFO

# Basic operations we can do on a queue are:

# Enqueue:  Adds a new element to the queue.
# Dequeue:  Removes and returns first (front) element from the queue.
# Peek:     Returns the first element in the queue.
# isEmpty:  Checks if the queue is empty.
# Size:     Finds the number of elements in the queue.  


